### ISSUE TITLE
Optimizing A instead of B

### ISSUE THREAD

**Issue by caal-15** [pin3da/gplib#21]
Trying to optimize the parameters in A instead of those in B

**Comment by caal-15** [comment]
@pin3da or @alsuga  please review

**Comment by pin3da** [comment]
Nice :+1: 
Now we need to avoid optimization of undesired parameters.

**Comment by pin3da** [comment]
Based on http://ab-initio.mit.edu/wiki/index.php/NLopt_Reference#Bound_constraints 

> "It is permitted to set lb[i] == ub[i] in one or more dimensions; this is equivalent to fixing the corresponding x[i] parameter, eliminating it from the optimization."

So, nlopt will not optimize undesired parameters.
