### ISSUE TITLE
Review Candela Likelihood

### ISSUE THREAD

**Issue by caal-15** [pin3da/gplib#27]
Please review carefully, our test seem to work, but it is slow

**Comment by pin3da** [comment]
I've just added new images for this likelihood 9135117dfb137ad899c7ae54f9c11be8bf6cc95f . I think we have something wrong because the regression is not smooth.

I'm still checking the code.

**Comment by pin3da** [comment]
Reference: http://jmlr.org/papers/volume6/quinonero-candela05a/quinonero-candela05a.pdf

**Comment by caal-15** [comment]
http://www.cyberneum.de/fileadmin/user_upload/files/publications/lskm_chap_%5B0%5D.pdf

**Comment by pin3da** [comment]
The problem with Log marginal likelihood was finally solved here b2419e35fad00f7e44
